<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="com.qa.Test.loginTest" duration-ms="28133" started-at="2020-06-03T20:04:37Z" finished-at="2020-06-03T20:05:05Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="28133" started-at="2020-06-03T20:04:37Z" finished-at="2020-06-03T20:05:05Z">
      <class name="com.qa.Test.loginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.Test.loginTest@4c70fda8]" name="setUp" is-config="true" duration-ms="15041" started-at="2020-06-04T01:34:37Z" finished-at="2020-06-04T01:34:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="TitleTextTest()[pri:1, instance:com.qa.Test.loginTest@4c70fda8]" name="TitleTextTest" duration-ms="101" started-at="2020-06-04T01:34:52Z" finished-at="2020-06-04T01:34:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO CRM Software for customer relationship management, sales and support.] but found [CRMPRO - CRM software for customer relationship management, sales, and support.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO CRM Software for customer relationship management, sales and support.] but found [CRMPRO - CRM software for customer relationship management, sales, and support.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.qa.Test.loginTest.TitleTextTest(loginTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TitleTextTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.Test.loginTest@4c70fda8]" name="tearDown" is-config="true" duration-ms="991" started-at="2020-06-04T01:34:52Z" finished-at="2020-06-04T01:34:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.Test.loginTest@4c70fda8]" name="setUp" is-config="true" duration-ms="10822" started-at="2020-06-04T01:34:53Z" finished-at="2020-06-04T01:35:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="isDisplayedLogo()[pri:1, instance:com.qa.Test.loginTest@4c70fda8]" name="isDisplayedLogo" duration-ms="351" started-at="2020-06-04T01:35:04Z" finished-at="2020-06-04T01:35:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isDisplayedLogo -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.Test.loginTest@4c70fda8]" name="tearDown" is-config="true" duration-ms="802" started-at="2020-06-04T01:35:04Z" finished-at="2020-06-04T01:35:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.Test.loginTest -->
    </test> <!-- Command line test -->
  </suite> <!-- com.qa.Test.loginTest -->
</testng-results>
